# Generated by Django 4.2.5 on 2023-09-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0002_alter_sponsor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr')], max_length=50)),
                ('institute', models.CharField(max_length=125)),
                ('contract_amount', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='StudentSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sponsors.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(related_name='students', through='students.StudentSponsor', to='sponsors.sponsor'),
        ),
    ]
